name: Check CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  run:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - arch: x86_64
            cc: gcc
            emulator: ""
            test_input: "Hello from x86_64"
          - arch: aarch64
            cc: aarch64-linux-gnu-gcc
            emulator: "qemu-aarch64"
            test_input: "Hello from AArch64"

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y gcc-aarch64-linux-gnu \
                            gcc-x86-64-linux-gnu  \
                            make                  \
                            qemu-user             \
                            libc6-arm64-cross     \
                            libc6-dev-arm64-cross

    - name: Setup AArch64 Environment
      if: matrix.arch == 'aarch64'
      run: |
        find / -name ld-linux-aarch64.so.1 2>/dev/null
        sudo mkdir -p /lib
        sudo ln -sf /usr /lib
        ls -la /lib/ld-linux-aarch64.so.1

    - name: Test generated assembly
      run: make ARCH=${{ matrix.arch }} test-asm

    - name: Test executable
      run: echo "${{ matrix.test_input }}" | make ARCH=${{ matrix.arch}} CC=${{ matrix.cc }} EMULATOR=${{ matrix.emulator }} test-exec
