name: Check CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  run:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [aarch64, x86_64]

    steps:
    - uses: actions/checkout@v4

    - name: Set CC Based on Targeted Architecture
      run: |
        case "${{ matrix.arch }}" in
          x86_64)
            echo "CC=gcc" >> $GITHUB_ENV
            ;;
          aarch64)
            echo "CC=aarch64-linux-gnu-gcc" >> $GITHUB_ENV
            ;;
        esac

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y gcc-aarch64-linux-gnu \
                            gcc-x86-64-linux-gnu  \
                            make                  \
                            qemu-user             \
                            libc6-arm64-cross     \
                            libc6-dev-arm64-cross

    - name: Test generated assembly
      run: |
        make ARCH=${{ matrix.arch }} test-asm

    - name: Test executable
      run: |
        case "${{ matrix.arch }}" in
          x86_64)
            echo "Hello from x86_64" | make ARCH=${{ matrix.arch }} CC=${{ env.CC }} test-exec
            ;;
          aarch64)
            sudo dpkg --add-architecture arm64
            echo "Hello from AArch64" | make ARCH=${{ matrix.arch }} CC=${{ env.CC }} EMULATOR="qemu-aarch64 -L /usr/aarch64-linux-gnu" test-exec
            ;;
        esac
