name: CI Check

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - arch: x86_64
            cc: gcc
            emulator: ""
            test_input: "Hello from x86_64"
          - arch: aarch64
            cc: aarch64-linux-gnu-gcc
            emulator: "qemu-aarch64-static"
            test_input: "Hello from AArch64"
          - arch: aarch32
            cc: arm-linux-gnueabihf-gcc
            emulator: "qemu-arm-static"
            test_input: "Hello from AArch32"
          - arch: i386
            cc: i686-linux-gnu-gcc
            emulator: "qemu-i386-static"
            test_input: "Hello from i386"
    steps:
    - uses: actions/checkout@v4

    - name: Installing dependencies
      run: |
        sudo apt update
        sudo apt install -y gcc                   \
                            make                  \
                            clang

    - name: Installing Qemu for non-x86_64 testing architecture
      if: matrix.arch != 'x86_64'
      run: sudo apt install -y qemu-user-static

    - name: Setup AArch64 Environment Testing
      if: matrix.arch == 'aarch64'
      run: |
        sudo dpkg --add-architecture aarch64
        sudo apt update
        sudo apt install libc:arm64
        sudo apt install -y gcc-aarch64-linux-gnu

    - name: Setup AArch32 Environment Testing
      if: matrix.arch == 'aarch32'
      run: |
        sudo dpkg --add-architecture arm32
        sudo apt update
        sudo apt install -y gcc-arm-linux-gnueabihf

    - name: Setup i386 Environment Testing
      if: matrix.arch == 'i386'
      run: |
        sudo dpkg --add-architecture amd32
        sudo apt update
        sudo apt install -y gcc-i686-linux-gnu

    - name: Test all
      run: make ARCH=${{ matrix.arch}} CC=${{ matrix.cc }} EMULATOR="${{ matrix.emulator }}" TEST_INPUT="${{ matrix.test_input }}" PREFIX_DEBUG=-asan test-all
