name: Mirror

on:
  schedule:
    - cron: '0 * * * *'

  workflow_dispatch:

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Push to Codeberg
        run: |
          git remote add codeberg https://Vgwws:${{ secrets.CODEBERG_TOKEN }}@codeberg.org/Vgwws/bfc.git
          git push --mirror codeberg
